source('pttTestFunction.R')
id = c(1:3)
URL = paste0("https://www.ptt.cc/bbs/Makeup/index", id, ".html")
filename = paste0(id, ".txt")
pttTestFunction(URL[1], filename[1])
mapply(pttTestFunction, 
       URL = URL, filename = filename)

rm(list=ls(all.names = TRUE))
library(NLP)
library(tm)
library(jiebaRD)
library(jiebaR)
library(RColorBrewer)
library(wordcloud)
filenames <- list.files(getwd(), pattern="*.txt")
files <- lapply(filenames, readLines)
docs <- Corpus(VectorSource(files))
toSpace <- content_transformer(function(x, pattern) {
  return (gsub(pattern, " ", x))
}
)
docs <- tm_map(docs, toSpace, "※")
docs <- tm_map(docs, toSpace, "◆")
docs <- tm_map(docs, toSpace, "‧")
docs <- tm_map(docs, toSpace, "的")
docs <- tm_map(docs, toSpace, "我")
docs <- tm_map(docs, toSpace, "是")
docs <- tm_map(docs, toSpace, "看板")
docs <- tm_map(docs, toSpace, "作者")
docs <- tm_map(docs, toSpace, "發信站")
docs <- tm_map(docs, toSpace, "批踢踢實業坊")
docs <- tm_map(docs, toSpace, "[a-zA-Z]")
docs <- tm_map(docs, toSpace, "大")
docs <- tm_map(docs, toSpace, "小")
docs <- tm_map(docs, toSpace, "可以")
docs <- tm_map(docs, toSpace, "大家")
docs <- tm_map(docs, toSpace, "來自")
docs <- tm_map(docs, toSpace, "不")
docs <- tm_map(docs, toSpace, "有")
docs <- tm_map(docs, toSpace, "From")
docs <- tm_map(docs, toSpace, "推")
docs <- tm_map(docs, toSpace, "會")
docs <- tm_map(docs, toSpace, "你")

docs <- tm_map(docs, removePunctuation)
docs <- tm_map(docs, removeNumbers)
docs <- tm_map(docs, stripWhitespace)
docs